//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hourglass.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hourglass.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Close.
        /// </summary>
        public static string AboutDialogCloseButtonContent {
            get {
                return ResourceManager.GetString("AboutDialogCloseButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contribute on GitHub:.
        /// </summary>
        public static string AboutDialogContributeOnGitHub {
            get {
                return ResourceManager.GetString("AboutDialogContributeOnGitHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License:.
        /// </summary>
        public static string AboutDialogLicense {
            get {
                return ResourceManager.GetString("AboutDialogLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More information:.
        /// </summary>
        public static string AboutDialogMoreInformation {
            get {
                return ResourceManager.GetString("AboutDialogMoreInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Hourglass.
        /// </summary>
        public static string AboutDialogTitle {
            get {
                return ResourceManager.GetString("AboutDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon AppIcon {
            get {
                object obj = ResourceManager.GetObject("AppIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hourglass.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream BeepLoud {
            get {
                return ResourceManager.GetStream("BeepLoud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream BeepNormal {
            get {
                return ResourceManager.GetStream("BeepNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream BeepQuiet {
            get {
                return ResourceManager.GetStream("BeepQuiet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate switch &quot;{0}&quot;.
        /// </summary>
        public static string CommandLineArgumentsParseExceptionDuplicateSwitchFormatString {
            get {
                return ResourceManager.GetString("CommandLineArgumentsParseExceptionDuplicateSwitchFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid timer input &quot;{0}&quot;.
        /// </summary>
        public static string CommandLineArgumentsParseExceptionInvalidTimerInputFormatString {
            get {
                return ResourceManager.GetString("CommandLineArgumentsParseExceptionInvalidTimerInputFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value &quot;{1}&quot; for switch &quot;{0}&quot;.
        /// </summary>
        public static string CommandLineArgumentsParseExceptionInvalidValueForSwitchFormatString {
            get {
                return ResourceManager.GetString("CommandLineArgumentsParseExceptionInvalidValueForSwitchFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing value for switch &quot;{0}&quot;.
        /// </summary>
        public static string CommandLineArgumentsParseExceptionMissingValueForSwitchFormatString {
            get {
                return ResourceManager.GetString("CommandLineArgumentsParseExceptionMissingValueForSwitchFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized switch &quot;{0}&quot;.
        /// </summary>
        public static string CommandLineArgumentsParseExceptionUnrecognizedSwitchFormatString {
            get {
                return ResourceManager.GetString("CommandLineArgumentsParseExceptionUnrecognizedSwitchFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _About.
        /// </summary>
        public static string ContextMenuAboutMenuItem {
            get {
                return ResourceManager.GetString("ContextMenuAboutMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced options.
        /// </summary>
        public static string ContextMenuAdvancedOptionsMenuItem {
            get {
                return ResourceManager.GetString("ContextMenuAdvancedOptionsMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Al_ways on top.
        /// </summary>
        public static string ContextMenuAlwaysOnTopMenuItem {
            get {
                return ResourceManager.GetString("ContextMenuAlwaysOnTopMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Application name.
        /// </summary>
        public static string ContextMenuApplicationNameWindowTitleMenuItem {
            get {
                return ResourceManager.GetString("ContextMenuApplicationNameWindowTitleMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Clear recent inputs.
        /// </summary>
        public static string ContextMenuClearRecentInputsMenuItem {
            get {
                return ResourceManager.GetString("ContextMenuClearRecentInputsMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Clear saved timers.
        /// </summary>
        public static string ContextMenuClearSavedTimersMenuItem {
            get {
                return ResourceManager.GetString("ContextMenuClearSavedTimersMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Close.
        /// </summary>
        public static string ContextMenuCloseMenuItem {
            get {
                return ResourceManager.GetString("ContextMenuCloseMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close when _expired.
        /// </summary>
        public static string ContextMenuCloseWhenExpiredMenuItem {
            get {
                return ResourceManager.GetString("ContextMenuCloseWhenExpiredMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Dark theme.
        /// </summary>
        public static string ContextMenuDarkThemeMenuItem {
            get {
                return ResourceManager.GetString("ContextMenuDarkThemeMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not _keep computer awake.
        /// </summary>
        public static string ContextMenuDoNotKeepComputerAwakeMenuItem {
            get {
                return ResourceManager.GetString("ContextMenuDoNotKeepComputerAwakeMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Full screen.
        /// </summary>
        public static string ContextMenuFullScreenMenuItem {
            get {
                return ResourceManager.GetString("ContextMenuFullScreenMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Light theme.
        /// </summary>
        public static string ContextMenuLightThemeMenuItem {
            get {
                return ResourceManager.GetString("ContextMenuLightThemeMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Loop sound.
        /// </summary>
        public static string ContextMenuLoopSoundMenuItem {
            get {
                return ResourceManager.GetString("ContextMenuLoopSoundMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Loop timer.
        /// </summary>
        public static string ContextMenuLoopTimerMenuItem {
            get {
                return ResourceManager.GetString("ContextMenuLoopTimerMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Manage themes....
        /// </summary>
        public static string ContextMenuManageThemesMenuItem {
            get {
                return ResourceManager.GetString("ContextMenuManageThemesMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ma_ximize.
        /// </summary>
        public static string ContextMenuMaximizeMenuItem {
            get {
                return ResourceManager.GetString("ContextMenuMaximizeMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Minimize.
        /// </summary>
        public static string ContextMenuMinimizeMenuItem {
            get {
                return ResourceManager.GetString("ContextMenuMinimizeMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _New timer.
        /// </summary>
        public static string ContextMenuNewTimerMenuItem {
            get {
                return ResourceManager.GetString("ContextMenuNewTimerMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No recent inputs.
        /// </summary>
        public static string ContextMenuNoRecentInputsMenuItem {
            get {
                return ResourceManager.GetString("ContextMenuNoRecentInputsMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No saved timers.
        /// </summary>
        public static string ContextMenuNoSavedTimersMenuItem {
            get {
                return ResourceManager.GetString("ContextMenuNoSavedTimersMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _No sound.
        /// </summary>
        public static string ContextMenuNoSoundMenuItem {
            get {
                return ResourceManager.GetString("ContextMenuNoSoundMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _None.
        /// </summary>
        public static string ContextMenuNoWindowTitleMenuItem {
            get {
                return ResourceManager.GetString("ContextMenuNoWindowTitleMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Open all saved timers.
        /// </summary>
        public static string ContextMenuOpenAllSavedTimersMenuItem {
            get {
                return ResourceManager.GetString("ContextMenuOpenAllSavedTimersMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Open saved timers on startup.
        /// </summary>
        public static string ContextMenuOpenSavedTimersOnStartupMenuItem {
            get {
                return ResourceManager.GetString("ContextMenuOpenSavedTimersOnStartupMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Pop up when expired.
        /// </summary>
        public static string ContextMenuPopUpWhenExpiredMenuItem {
            get {
                return ResourceManager.GetString("ContextMenuPopUpWhenExpiredMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefer 24-_hour time when parsing.
        /// </summary>
        public static string ContextMenuPrefer24HourTimeMenuItem {
            get {
                return ResourceManager.GetString("ContextMenuPrefer24HourTimeMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pro_mpt on exit.
        /// </summary>
        public static string ContextMenuPromptOnExitMenuItem {
            get {
                return ResourceManager.GetString("ContextMenuPromptOnExitMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Recent inputs.
        /// </summary>
        public static string ContextMenuRecentInputsMenuItem {
            get {
                return ResourceManager.GetString("ContextMenuRecentInputsMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rest_ore.
        /// </summary>
        public static string ContextMenuRestoreMenuItem {
            get {
                return ResourceManager.GetString("ContextMenuRestoreMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Reverse progress bar.
        /// </summary>
        public static string ContextMenuReverseProgressBarMenuItem {
            get {
                return ResourceManager.GetString("ContextMenuReverseProgressBarMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sa_ved timers.
        /// </summary>
        public static string ContextMenuSavedTimersMenuItem {
            get {
                return ResourceManager.GetString("ContextMenuSavedTimersMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S_how in notification area.
        /// </summary>
        public static string ContextMenuShowInNotificationAreaMenuItem {
            get {
                return ResourceManager.GetString("ContextMenuShowInNotificationAreaMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show progress in taskbar.
        /// </summary>
        public static string ContextMenuShowProgressInTaskbarMenuItem {
            get {
                return ResourceManager.GetString("ContextMenuShowProgressInTaskbarMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Show time elapsed instead of time left.
        /// </summary>
        public static string ContextMenuShowTimeElapsedMenuItem {
            get {
                return ResourceManager.GetString("ContextMenuShowTimeElapsedMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shut _down when expired.
        /// </summary>
        public static string ContextMenuShutDownWhenExpiredMenuItem {
            get {
                return ResourceManager.GetString("ContextMenuShutDownWhenExpiredMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Sound.
        /// </summary>
        public static string ContextMenuSoundMenuItem {
            get {
                return ResourceManager.GetString("ContextMenuSoundMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Theme.
        /// </summary>
        public static string ContextMenuThemeMenuItem {
            get {
                return ResourceManager.GetString("ContextMenuThemeMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time ela_psed · Timer title.
        /// </summary>
        public static string ContextMenuTimeElapsedPlusTimerTitleWindowTitleMenuItem {
            get {
                return ResourceManager.GetString("ContextMenuTimeElapsedPlusTimerTitleWindowTitleMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time _elapsed.
        /// </summary>
        public static string ContextMenuTimeElapsedWindowTitleMenuItem {
            get {
                return ResourceManager.GetString("ContextMenuTimeElapsedWindowTitleMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time le_ft · Timer title.
        /// </summary>
        public static string ContextMenuTimeLeftPlusTimerTitleWindowTitleMenuItem {
            get {
                return ResourceManager.GetString("ContextMenuTimeLeftPlusTimerTitleWindowTitleMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time _left.
        /// </summary>
        public static string ContextMenuTimeLeftWindowTitleMenuItem {
            get {
                return ResourceManager.GetString("ContextMenuTimeLeftWindowTitleMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ti_mer title · Time elapsed.
        /// </summary>
        public static string ContextMenuTimerTitlePlusTimeElapsedWindowTitleMenuItem {
            get {
                return ResourceManager.GetString("ContextMenuTimerTitlePlusTimeElapsedWindowTitleMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T_imer title · Time left.
        /// </summary>
        public static string ContextMenuTimerTitlePlusTimeLeftWindowTitleMenuItem {
            get {
                return ResourceManager.GetString("ContextMenuTimerTitlePlusTimeLeftWindowTitleMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer _title.
        /// </summary>
        public static string ContextMenuTimerTitleWindowTitleMenuItem {
            get {
                return ResourceManager.GetString("ContextMenuTimerTitleWindowTitleMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unnamed theme.
        /// </summary>
        public static string ContextMenuUnnamedTheme {
            get {
                return ResourceManager.GetString("ContextMenuUnnamedTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Window title.
        /// </summary>
        public static string ContextMenuWindowTitleMenuItem {
            get {
                return ResourceManager.GetString("ContextMenuWindowTitleMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string CultureName {
            get {
                return ResourceManager.GetString("CultureName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to April.
        /// </summary>
        public static string DateTimeExtensionsApril {
            get {
                return ResourceManager.GetString("DateTimeExtensionsApril", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to August.
        /// </summary>
        public static string DateTimeExtensionsAugust {
            get {
                return ResourceManager.GetString("DateTimeExtensionsAugust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to December.
        /// </summary>
        public static string DateTimeExtensionsDecember {
            get {
                return ResourceManager.GetString("DateTimeExtensionsDecember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to February.
        /// </summary>
        public static string DateTimeExtensionsFebruary {
            get {
                return ResourceManager.GetString("DateTimeExtensionsFebruary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to January.
        /// </summary>
        public static string DateTimeExtensionsJanuary {
            get {
                return ResourceManager.GetString("DateTimeExtensionsJanuary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to July.
        /// </summary>
        public static string DateTimeExtensionsJuly {
            get {
                return ResourceManager.GetString("DateTimeExtensionsJuly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to June.
        /// </summary>
        public static string DateTimeExtensionsJune {
            get {
                return ResourceManager.GetString("DateTimeExtensionsJune", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to March.
        /// </summary>
        public static string DateTimeExtensionsMarch {
            get {
                return ResourceManager.GetString("DateTimeExtensionsMarch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to May.
        /// </summary>
        public static string DateTimeExtensionsMay {
            get {
                return ResourceManager.GetString("DateTimeExtensionsMay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}nd.
        /// </summary>
        public static string DateTimeExtensionsNndFormatString {
            get {
                return ResourceManager.GetString("DateTimeExtensionsNndFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to November.
        /// </summary>
        public static string DateTimeExtensionsNovember {
            get {
                return ResourceManager.GetString("DateTimeExtensionsNovember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}rd.
        /// </summary>
        public static string DateTimeExtensionsNrdFormatString {
            get {
                return ResourceManager.GetString("DateTimeExtensionsNrdFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}st.
        /// </summary>
        public static string DateTimeExtensionsNstFormatString {
            get {
                return ResourceManager.GetString("DateTimeExtensionsNstFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}th.
        /// </summary>
        public static string DateTimeExtensionsNthFormatString {
            get {
                return ResourceManager.GetString("DateTimeExtensionsNthFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to October.
        /// </summary>
        public static string DateTimeExtensionsOctober {
            get {
                return ResourceManager.GetString("DateTimeExtensionsOctober", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to September.
        /// </summary>
        public static string DateTimeExtensionsSeptember {
            get {
                return ResourceManager.GetString("DateTimeExtensionsSeptember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        public static string DateTimeTokenDateOnlyFormatString {
            get {
                return ResourceManager.GetString("DateTimeTokenDateOnlyFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^({0})$.
        /// </summary>
        public static string DateTimeTokenDateOnlyPatternFormatString {
            get {
                return ResourceManager.GetString("DateTimeTokenDateOnlyPatternFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} at {1}.
        /// </summary>
        public static string DateTimeTokenDateTimeFormatString {
            get {
                return ResourceManager.GetString("DateTimeTokenDateTimeFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^({0})\s+(at\s+)?({1})$.
        /// </summary>
        public static string DateTimeTokenDateTimePatternFormatString {
            get {
                return ResourceManager.GetString("DateTimeTokenDateTimePatternFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^({0})\s+(on\s+)?({1})$.
        /// </summary>
        public static string DateTimeTokenTimeDatePatternFormatString {
            get {
                return ResourceManager.GetString("DateTimeTokenTimeDatePatternFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to until {0}.
        /// </summary>
        public static string DateTimeTokenTimeOnlyFormatString {
            get {
                return ResourceManager.GetString("DateTimeTokenTimeOnlyFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^({0})$.
        /// </summary>
        public static string DateTimeTokenTimeOnlyPatternFormatString {
            get {
                return ResourceManager.GetString("DateTimeTokenTimeOnlyPatternFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} after next.
        /// </summary>
        public static string DayOfWeekDateTokenAfterNextFormatString {
            get {
                return ResourceManager.GetString("DayOfWeekDateTokenAfterNextFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?&lt;weekday&gt;(Sun|Mon|Tue|Wed|Thu|Fri|Sat)[a-z]*)
        ///(\s*after)?
        ///\s*(?&lt;afternext&gt;next).
        /// </summary>
        public static string DayOfWeekDateTokenDaysOfWeekAfterNextPattern {
            get {
                return ResourceManager.GetString("DayOfWeekDateTokenDaysOfWeekAfterNextPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ((this|next)\s*)?
        ///(?&lt;weekday&gt;(Sun|Mon|Tue|Wed|Thu|Fri|Sat)[a-z]*).
        /// </summary>
        public static string DayOfWeekDateTokenDaysOfWeekNextPattern {
            get {
                return ResourceManager.GetString("DayOfWeekDateTokenDaysOfWeekNextPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?&lt;weekday&gt;(Sun|Mon|Tue|Wed|Thu|Fri|Sat)[a-z]*)
        ///\s*(?&lt;nextweek&gt;next\s*w(ee)?k).
        /// </summary>
        public static string DayOfWeekDateTokenDaysOfWeekNextWeekPattern {
            get {
                return ResourceManager.GetString("DayOfWeekDateTokenDaysOfWeekNextWeekPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        public static string DayOfWeekDateTokenNextFormatString {
            get {
                return ResourceManager.GetString("DayOfWeekDateTokenNextFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} next week.
        /// </summary>
        public static string DayOfWeekDateTokenNextWeekFormatString {
            get {
                return ResourceManager.GetString("DayOfWeekDateTokenNextWeekFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friday.
        /// </summary>
        public static string DayOfWeekExtensionsFriday {
            get {
                return ResourceManager.GetString("DayOfWeekExtensionsFriday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday.
        /// </summary>
        public static string DayOfWeekExtensionsMonday {
            get {
                return ResourceManager.GetString("DayOfWeekExtensionsMonday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday.
        /// </summary>
        public static string DayOfWeekExtensionsSaturday {
            get {
                return ResourceManager.GetString("DayOfWeekExtensionsSaturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunday.
        /// </summary>
        public static string DayOfWeekExtensionsSunday {
            get {
                return ResourceManager.GetString("DayOfWeekExtensionsSunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thursday.
        /// </summary>
        public static string DayOfWeekExtensionsThursday {
            get {
                return ResourceManager.GetString("DayOfWeekExtensionsThursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuesday.
        /// </summary>
        public static string DayOfWeekExtensionsTuesday {
            get {
                return ResourceManager.GetString("DayOfWeekExtensionsTuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wednesday.
        /// </summary>
        public static string DayOfWeekExtensionsWednesday {
            get {
                return ResourceManager.GetString("DayOfWeekExtensionsWednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Close.
        /// </summary>
        public static string ErrorDialogCloseButtonContent {
            get {
                return ResourceManager.GetString("ErrorDialogCloseButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error has occurred.
        /// </summary>
        public static string ErrorDialogDefaultMessageText {
            get {
                return ResourceManager.GetString("ErrorDialogDefaultMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Show details.
        /// </summary>
        public static string ErrorDialogShowDetailsButtonContent {
            get {
                return ResourceManager.GetString("ErrorDialogShowDetailsButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hourglass.
        /// </summary>
        public static string ErrorDialogTitle {
            get {
                return ResourceManager.GetString("ErrorDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The error has been written to &quot;{0}&quot;..
        /// </summary>
        public static string ErrorManagerErrorHasBeenWritten {
            get {
                return ResourceManager.GetString("ErrorManagerErrorHasBeenWritten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to clean old error messages..
        /// </summary>
        public static string ErrorManagerFailedToClean {
            get {
                return ResourceManager.GetString("ErrorManagerFailedToClean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error has occurred.
        /// </summary>
        public static string ErrorManagerUnexpectedError {
            get {
                return ResourceManager.GetString("ErrorManagerUnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIT License
        ///
        ///Copyright © 2021 Chris Dziemborowicz
        ///
        ///Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the &quot;Software&quot;), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
        ///
        ///The above copyright n [rest of string was truncated]&quot;;.
        /// </summary>
        public static string License {
            get {
                return ResourceManager.GetString("License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hourglass.
        /// </summary>
        public static string MessageBoxTitle {
            get {
                return ResourceManager.GetString("MessageBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1}.
        /// </summary>
        public static string NormalDateTokenDayAndMonthFormatString {
            get {
                return ResourceManager.GetString("NormalDateTokenDayAndMonthFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} {2}.
        /// </summary>
        public static string NormalDateTokenDayMonthAndYearFormatString {
            get {
                return ResourceManager.GetString("NormalDateTokenDayMonthAndYearFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        public static string NormalDateTokenDayOnlyFormatString {
            get {
                return ResourceManager.GetString("NormalDateTokenDayOnlyFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (the\s*)?
        ///(?&lt;day&gt;\d\d?)
        ///(\s*(st|nd|rd|th)).
        /// </summary>
        public static string NormalDateTokenDayOnlyPattern {
            get {
                return ResourceManager.GetString("NormalDateTokenDayOnlyPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1} {0}.
        /// </summary>
        public static string NormalDateTokenMonthAndDayFormatString {
            get {
                return ResourceManager.GetString("NormalDateTokenMonthAndDayFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1}.
        /// </summary>
        public static string NormalDateTokenMonthAndYearFormatString {
            get {
                return ResourceManager.GetString("NormalDateTokenMonthAndYearFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1} {0}, {2}.
        /// </summary>
        public static string NormalDateTokenMonthDayAndYearFormatString {
            get {
                return ResourceManager.GetString("NormalDateTokenMonthDayAndYearFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        public static string NormalDateTokenMonthOnlyFormatString {
            get {
                return ResourceManager.GetString("NormalDateTokenMonthOnlyFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?&lt;day&gt;\d\d?)
        ///[.\-/]
        ///(?&lt;month&gt;\d\d?)
        ///(
        ///    [.\-/]
        ///    (?&lt;year&gt;(\d\d)?\d\d)
        ///)?.
        /// </summary>
        public static string NormalDateTokenNumericalDateWithDayFirstPattern {
            get {
                return ResourceManager.GetString("NormalDateTokenNumericalDateWithDayFirstPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?&lt;month&gt;\d\d?)
        ///[.\-/]
        ///(?&lt;day&gt;\d\d?)
        ///(
        ///    [.\-/]
        ///    (?&lt;year&gt;(\d\d)?\d\d)
        ///)?.
        /// </summary>
        public static string NormalDateTokenNumericalDateWithMonthFirstPattern {
            get {
                return ResourceManager.GetString("NormalDateTokenNumericalDateWithMonthFirstPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (
        ///    (?&lt;year&gt;(\d\d)?\d\d)
        ///    [.\-/]
        ///)?
        ///(?&lt;month&gt;\d\d?)
        ///[.\-/]
        ///(?&lt;day&gt;\d\d?).
        /// </summary>
        public static string NormalDateTokenNumericalDateWithYearFirstPattern {
            get {
                return ResourceManager.GetString("NormalDateTokenNumericalDateWithYearFirstPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?&lt;month&gt;\d\d?)
        ///[.\-/]
        ///(?&lt;year&gt;\d\d\d\d)
        ///|
        ///(?&lt;year&gt;\d\d\d\d)
        ///[.\-/]
        ///(?&lt;month&gt;\d\d?).
        /// </summary>
        public static string NormalDateTokenNumericalMonthAndYearPattern {
            get {
                return ResourceManager.GetString("NormalDateTokenNumericalMonthAndYearPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?&lt;day&gt;\d\d?)
        ///(\s*(st|nd|rd|th))?
        ///(\s*of)?
        ///\s*(?&lt;month&gt;(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)[a-z]*)
        ///(
        ///    \s*,?\s*
        ///    (?&lt;year&gt;(\d\d)?\d\d)
        ///)?.
        /// </summary>
        public static string NormalDateTokenSpelledDateWithDayFirstPattern {
            get {
                return ResourceManager.GetString("NormalDateTokenSpelledDateWithDayFirstPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?&lt;month&gt;(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)[a-z]*)
        ///\s*(?&lt;day&gt;\d\d?)
        ///(\s*(st|nd|rd|th))?
        ///(
        ///    \s*[\s,]\s*
        ///    (?&lt;year&gt;(\d\d)?\d\d)
        ///)?.
        /// </summary>
        public static string NormalDateTokenSpelledDateWithMonthFirstPattern {
            get {
                return ResourceManager.GetString("NormalDateTokenSpelledDateWithMonthFirstPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?&lt;month&gt;(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)[a-z]*)
        ///(
        ///    \s*,?\s*
        ///    (?&lt;year&gt;\d\d\d\d)
        ///)?.
        /// </summary>
        public static string NormalDateTokenSpelledMonthAndOptionalYearPattern {
            get {
                return ResourceManager.GetString("NormalDateTokenSpelledMonthAndOptionalYearPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        public static string NormalDateTokenYearOnlyFormatString {
            get {
                return ResourceManager.GetString("NormalDateTokenYearOnlyFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  am.
        /// </summary>
        public static string NormalTimeTokenAmSuffix {
            get {
                return ResourceManager.GetString("NormalTimeTokenAmSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        public static string NormalTimeTokenHourPartFormatString {
            get {
                return ResourceManager.GetString("NormalTimeTokenHourPartFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  noon.
        /// </summary>
        public static string NormalTimeTokenMiddaySuffix {
            get {
                return ResourceManager.GetString("NormalTimeTokenMiddaySuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  midnight.
        /// </summary>
        public static string NormalTimeTokenMidnightSuffix {
            get {
                return ResourceManager.GetString("NormalTimeTokenMidnightSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?&lt;hour&gt;\d\d)
        ///(?&lt;minute&gt;\d\d)
        ///(?&lt;military&gt;|h|hrs|hours).
        /// </summary>
        public static string NormalTimeTokenMilitaryTimePattern {
            get {
                return ResourceManager.GetString("NormalTimeTokenMilitaryTimePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :{0:00}.
        /// </summary>
        public static string NormalTimeTokenMinutePartFormatString {
            get {
                return ResourceManager.GetString("NormalTimeTokenMinutePartFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  pm.
        /// </summary>
        public static string NormalTimeTokenPmSuffix {
            get {
                return ResourceManager.GetString("NormalTimeTokenPmSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :{0:00}.
        /// </summary>
        public static string NormalTimeTokenSecondPartFormatString {
            get {
                return ResourceManager.GetString("NormalTimeTokenSecondPartFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?&lt;hour&gt;\d\d?)
        ///(
        ///    (?&lt;minute&gt;\d\d)
        ///    (?&lt;second&gt;\d\d)?
        ///)?
        ///\s*
        ///(
        ///    (?&lt;am&gt;a\.?(\s*m\.?)?)
        ///    |
        ///    (?&lt;pm&gt;p\.?(\s*m\.?)?)
        ///    |
        ///    (?&lt;military&gt;h|hrs|hours)
        ///    |
        ///    o&apos;?clock
        ///)?.
        /// </summary>
        public static string NormalTimeTokenTimeWithoutSeparatorsPattern {
            get {
                return ResourceManager.GetString("NormalTimeTokenTimeWithoutSeparatorsPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?&lt;hour&gt;\d\d?)
        ///(
        ///    [.:]
        ///    (?&lt;minute&gt;\d\d?)
        ///    (
        ///        [.:]
        ///        (?&lt;second&gt;\d\d?)
        ///    )?
        ///)?
        ///\s*
        ///(
        ///    (?&lt;am&gt;a\.?(\s*m\.?)?)
        ///    |
        ///    (?&lt;pm&gt;p\.?(\s*m\.?)?)
        ///    |
        ///    (?&lt;military&gt;h|hrs|hours)
        ///    |
        ///    o&apos;?clock
        ///)?.
        /// </summary>
        public static string NormalTimeTokenTimeWithSeparatorsPattern {
            get {
                return ResourceManager.GetString("NormalTimeTokenTimeWithSeparatorsPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E&amp;xit.
        /// </summary>
        public static string NotificationAreaIconExitMenuItem {
            get {
                return ResourceManager.GetString("NotificationAreaIconExitMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;New timer.
        /// </summary>
        public static string NotificationAreaIconNewTimerMenuItem {
            get {
                return ResourceManager.GetString("NotificationAreaIconNewTimerMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer expired.
        /// </summary>
        public static string NotificationAreaIconTimerExpired {
            get {
                return ResourceManager.GetString("NotificationAreaIconTimerExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your timer has expired..
        /// </summary>
        public static string NotificationAreaIconYourTimerHasExpired {
            get {
                return ResourceManager.GetString("NotificationAreaIconYourTimerHasExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to today.
        /// </summary>
        public static string RelativeDateTokenTodayName {
            get {
                return ResourceManager.GetString("RelativeDateTokenTodayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to todd?ay.
        /// </summary>
        public static string RelativeDateTokenTodayPattern {
            get {
                return ResourceManager.GetString("RelativeDateTokenTodayPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tomorrow.
        /// </summary>
        public static string RelativeDateTokenTomorrowName {
            get {
                return ResourceManager.GetString("RelativeDateTokenTomorrowName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tomm?orr?ow.
        /// </summary>
        public static string RelativeDateTokenTomorrowPattern {
            get {
                return ResourceManager.GetString("RelativeDateTokenTomorrowPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loud beep.
        /// </summary>
        public static string SoundManagerLoudBeep {
            get {
                return ResourceManager.GetString("SoundManagerLoudBeep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal beep.
        /// </summary>
        public static string SoundManagerNormalBeep {
            get {
                return ResourceManager.GetString("SoundManagerNormalBeep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quiet beep.
        /// </summary>
        public static string SoundManagerQuietBeep {
            get {
                return ResourceManager.GetString("SoundManagerQuietBeep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Christmas Day.
        /// </summary>
        public static string SpecialDateTokenChristmasDayName {
            get {
                return ResourceManager.GetString("SpecialDateTokenChristmasDayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (ch?rist?|x)-?mass?(\s*day)?.
        /// </summary>
        public static string SpecialDateTokenChristmasDayPattern {
            get {
                return ResourceManager.GetString("SpecialDateTokenChristmasDayPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Year.
        /// </summary>
        public static string SpecialDateTokenNewYearName {
            get {
                return ResourceManager.GetString("SpecialDateTokenNewYearName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ny|new\s*year.
        /// </summary>
        public static string SpecialDateTokenNewYearPattern {
            get {
                return ResourceManager.GetString("SpecialDateTokenNewYearPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Year&apos;s Eve.
        /// </summary>
        public static string SpecialDateTokenNewYearsEveName {
            get {
                return ResourceManager.GetString("SpecialDateTokenNewYearsEveName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nye|new\s*year(&apos;?s)?\s*eve.
        /// </summary>
        public static string SpecialDateTokenNewYearsEvePattern {
            get {
                return ResourceManager.GetString("SpecialDateTokenNewYearsEvePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12 noon.
        /// </summary>
        public static string SpecialTimeTokenMiddayName {
            get {
                return ResourceManager.GetString("SpecialTimeTokenMiddayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (12([.:]00([.:]00)?)?\s*)?(noon|mid(-?d)?ay).
        /// </summary>
        public static string SpecialTimeTokenMiddayPattern {
            get {
                return ResourceManager.GetString("SpecialTimeTokenMiddayPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12 midnight.
        /// </summary>
        public static string SpecialTimeTokenMidnightName {
            get {
                return ResourceManager.GetString("SpecialTimeTokenMidnightName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (12([.:]00([.:]00)?)?\s*)?mid-?night.
        /// </summary>
        public static string SpecialTimeTokenMidnightPattern {
            get {
                return ResourceManager.GetString("SpecialTimeTokenMidnightPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black.
        /// </summary>
        public static string ThemeManagerBlackDarkTheme {
            get {
                return ResourceManager.GetString("ThemeManagerBlackDarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black.
        /// </summary>
        public static string ThemeManagerBlackLightTheme {
            get {
                return ResourceManager.GetString("ThemeManagerBlackLightTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue.
        /// </summary>
        public static string ThemeManagerBlueDarkTheme {
            get {
                return ResourceManager.GetString("ThemeManagerBlueDarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue.
        /// </summary>
        public static string ThemeManagerBlueLightTheme {
            get {
                return ResourceManager.GetString("ThemeManagerBlueLightTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gray.
        /// </summary>
        public static string ThemeManagerGrayDarkTheme {
            get {
                return ResourceManager.GetString("ThemeManagerGrayDarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gray.
        /// </summary>
        public static string ThemeManagerGrayLightTheme {
            get {
                return ResourceManager.GetString("ThemeManagerGrayLightTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green.
        /// </summary>
        public static string ThemeManagerGreenDarkTheme {
            get {
                return ResourceManager.GetString("ThemeManagerGreenDarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green.
        /// </summary>
        public static string ThemeManagerGreenLightTheme {
            get {
                return ResourceManager.GetString("ThemeManagerGreenLightTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New theme.
        /// </summary>
        public static string ThemeManagerNewTheme {
            get {
                return ResourceManager.GetString("ThemeManagerNewTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orange.
        /// </summary>
        public static string ThemeManagerOrangeDarkTheme {
            get {
                return ResourceManager.GetString("ThemeManagerOrangeDarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orange.
        /// </summary>
        public static string ThemeManagerOrangeLightTheme {
            get {
                return ResourceManager.GetString("ThemeManagerOrangeLightTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purple.
        /// </summary>
        public static string ThemeManagerPurpleDarkTheme {
            get {
                return ResourceManager.GetString("ThemeManagerPurpleDarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purple.
        /// </summary>
        public static string ThemeManagerPurpleLightTheme {
            get {
                return ResourceManager.GetString("ThemeManagerPurpleLightTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        public static string ThemeManagerRedDarkTheme {
            get {
                return ResourceManager.GetString("ThemeManagerRedDarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        public static string ThemeManagerRedLightTheme {
            get {
                return ResourceManager.GetString("ThemeManagerRedLightTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark themes.
        /// </summary>
        public static string ThemeManagerWindowDarkThemesSectionHeader {
            get {
                return ResourceManager.GetString("ThemeManagerWindowDarkThemesSectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the selected theme?.
        /// </summary>
        public static string ThemeManagerWindowDeletePrompt {
            get {
                return ResourceManager.GetString("ThemeManagerWindowDeletePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light themes.
        /// </summary>
        public static string ThemeManagerWindowLightThemesSectionHeader {
            get {
                return ResourceManager.GetString("ThemeManagerWindowLightThemesSectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save the changes to the current theme?.
        /// </summary>
        public static string ThemeManagerWindowSavePrompt {
            get {
                return ResourceManager.GetString("ThemeManagerWindowSavePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom themes.
        /// </summary>
        public static string ThemeManagerWindowUserProvidedThemesSectionHeader {
            get {
                return ResourceManager.GetString("ThemeManagerWindowUserProvidedThemesSectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow.
        /// </summary>
        public static string ThemeManagerYellowDarkTheme {
            get {
                return ResourceManager.GetString("ThemeManagerYellowDarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow.
        /// </summary>
        public static string ThemeManagerYellowLightTheme {
            get {
                return ResourceManager.GetString("ThemeManagerYellowLightTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1} (Expired).
        /// </summary>
        public static string TimerExpiredFormatString {
            get {
                return ResourceManager.GetString("TimerExpiredFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1} (Expired).
        /// </summary>
        public static string TimerExpiredLoopedFormatString {
            get {
                return ResourceManager.GetString("TimerExpiredLoopedFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1} &quot;{2}&quot; (Expired).
        /// </summary>
        public static string TimerExpiredWithTitleFormatString {
            get {
                return ResourceManager.GetString("TimerExpiredWithTitleFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1} &quot;{2}&quot; (Expired).
        /// </summary>
        public static string TimerExpiredWithTitleLoopedFormatString {
            get {
                return ResourceManager.GetString("TimerExpiredWithTitleLoopedFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ➔ {1} (Paused).
        /// </summary>
        public static string TimerPausedFormatString {
            get {
                return ResourceManager.GetString("TimerPausedFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ➔ {1} (Paused).
        /// </summary>
        public static string TimerPausedLoopedFormatString {
            get {
                return ResourceManager.GetString("TimerPausedLoopedFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ➔ {1} &quot;{2}&quot; (Paused).
        /// </summary>
        public static string TimerPausedWithTitleFormatString {
            get {
                return ResourceManager.GetString("TimerPausedWithTitleFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ➔ {1} &quot;{2}&quot; (Paused).
        /// </summary>
        public static string TimerPausedWithTitleLoopedFormatString {
            get {
                return ResourceManager.GetString("TimerPausedWithTitleLoopedFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ➔ {1}.
        /// </summary>
        public static string TimerRunningFormatString {
            get {
                return ResourceManager.GetString("TimerRunningFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ➔ {1} (Looped).
        /// </summary>
        public static string TimerRunningLoopedFormatString {
            get {
                return ResourceManager.GetString("TimerRunningLoopedFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ➔ {1} &quot;{2}&quot;.
        /// </summary>
        public static string TimerRunningWithTitleFormatString {
            get {
                return ResourceManager.GetString("TimerRunningWithTitleFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ➔ {1} &quot;{2}&quot; (Looped).
        /// </summary>
        public static string TimerRunningWithTitleLoopedFormatString {
            get {
                return ResourceManager.GetString("TimerRunningWithTitleLoopedFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 minutes.
        /// </summary>
        public static string TimerStartDefault {
            get {
                return ResourceManager.GetString("TimerStartDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^\s*((un)?till?|@)\s*.
        /// </summary>
        public static string TimerStartTokenUseDateTimeParserPattern {
            get {
                return ResourceManager.GetString("TimerStartTokenUseDateTimeParserPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0 seconds.
        /// </summary>
        public static string TimerStartZero {
            get {
                return ResourceManager.GetString("TimerStartZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped.
        /// </summary>
        public static string TimerStoppedFormatString {
            get {
                return ResourceManager.GetString("TimerStoppedFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped.
        /// </summary>
        public static string TimerStoppedLoopedFormatString {
            get {
                return ResourceManager.GetString("TimerStoppedLoopedFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped &quot;{2}&quot;.
        /// </summary>
        public static string TimerStoppedWithTitleFormatString {
            get {
                return ResourceManager.GetString("TimerStoppedWithTitleFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped &quot;{2}&quot;.
        /// </summary>
        public static string TimerStoppedWithTitleLoopedFormatString {
            get {
                return ResourceManager.GetString("TimerStoppedWithTitleLoopedFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ago.
        /// </summary>
        public static string TimerTimeExpiredFormatString {
            get {
                return ResourceManager.GetString("TimerTimeExpiredFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer expired.
        /// </summary>
        public static string TimerTimerExpired {
            get {
                return ResourceManager.GetString("TimerTimerExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer not expired.
        /// </summary>
        public static string TimerTimerNotExpired {
            get {
                return ResourceManager.GetString("TimerTimerNotExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer stopped.
        /// </summary>
        public static string TimerTimerStopped {
            get {
                return ResourceManager.GetString("TimerTimerStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to —.
        /// </summary>
        public static string TimerWindowBlankTitlePlaceholder {
            get {
                return ResourceManager.GetString("TimerWindowBlankTitlePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Cancel.
        /// </summary>
        public static string TimerWindowCancelButtonContent {
            get {
                return ResourceManager.GetString("TimerWindowCancelButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Close.
        /// </summary>
        public static string TimerWindowCloseButtonContent {
            get {
                return ResourceManager.GetString("TimerWindowCloseButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to close this timer window?.
        /// </summary>
        public static string TimerWindowCloseMessageBoxText {
            get {
                return ResourceManager.GetString("TimerWindowCloseMessageBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To update Hourglass, visit {0} in your web browser..
        /// </summary>
        public static string TimerWindowCouldNotLaunchWebBrowserErrorMessage {
            get {
                return ResourceManager.GetString("TimerWindowCouldNotLaunchWebBrowserErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not launch web browser.
        /// </summary>
        public static string TimerWindowCouldNotLaunchWebBrowserErrorTitle {
            get {
                return ResourceManager.GetString("TimerWindowCouldNotLaunchWebBrowserErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New timer: {0} &quot;{1}&quot;.
        /// </summary>
        public static string TimerWindowNewTimerWithTitleFormatString {
            get {
                return ResourceManager.GetString("TimerWindowNewTimerWithTitleFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Pause.
        /// </summary>
        public static string TimerWindowPauseButtonContent {
            get {
                return ResourceManager.GetString("TimerWindowPauseButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Restart.
        /// </summary>
        public static string TimerWindowRestartButtonContent {
            get {
                return ResourceManager.GetString("TimerWindowRestartButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R_esume.
        /// </summary>
        public static string TimerWindowResumeButtonContent {
            get {
                return ResourceManager.GetString("TimerWindowResumeButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Start.
        /// </summary>
        public static string TimerWindowStartButtonContent {
            get {
                return ResourceManager.GetString("TimerWindowStartButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Stop.
        /// </summary>
        public static string TimerWindowStopButtonContent {
            get {
                return ResourceManager.GetString("TimerWindowStopButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to enter time or date.
        /// </summary>
        public static string TimerWindowTimerTextHint {
            get {
                return ResourceManager.GetString("TimerWindowTimerTextHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hourglass.
        /// </summary>
        public static string TimerWindowTitle {
            get {
                return ResourceManager.GetString("TimerWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  · .
        /// </summary>
        public static string TimerWindowTitleSeparator {
            get {
                return ResourceManager.GetString("TimerWindowTitleSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to enter title.
        /// </summary>
        public static string TimerWindowTitleTextHint {
            get {
                return ResourceManager.GetString("TimerWindowTitleTextHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Update.
        /// </summary>
        public static string TimerWindowUpdateButtonContent {
            get {
                return ResourceManager.GetString("TimerWindowUpdateButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New timer: {0}.
        /// </summary>
        public static string TimerWindwoNewTimerFormatString {
            get {
                return ResourceManager.GetString("TimerWindwoNewTimerFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} day.
        /// </summary>
        public static string TimeSpanExtensions1DayFormatString {
            get {
                return ResourceManager.GetString("TimeSpanExtensions1DayFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} hour.
        /// </summary>
        public static string TimeSpanExtensions1HourFormatString {
            get {
                return ResourceManager.GetString("TimeSpanExtensions1HourFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} minute.
        /// </summary>
        public static string TimeSpanExtensions1MinuteFormatString {
            get {
                return ResourceManager.GetString("TimeSpanExtensions1MinuteFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} second.
        /// </summary>
        public static string TimeSpanExtensions1SecondFormatString {
            get {
                return ResourceManager.GetString("TimeSpanExtensions1SecondFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} days.
        /// </summary>
        public static string TimeSpanExtensionsNDaysFormatString {
            get {
                return ResourceManager.GetString("TimeSpanExtensionsNDaysFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} hours.
        /// </summary>
        public static string TimeSpanExtensionsNHoursFormatString {
            get {
                return ResourceManager.GetString("TimeSpanExtensionsNHoursFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} minutes.
        /// </summary>
        public static string TimeSpanExtensionsNMinutesFormatString {
            get {
                return ResourceManager.GetString("TimeSpanExtensionsNMinutesFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} seconds.
        /// </summary>
        public static string TimeSpanExtensionsNSecondsFormatString {
            get {
                return ResourceManager.GetString("TimeSpanExtensionsNSecondsFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  .
        /// </summary>
        public static string TimeSpanExtensionsUnitSeparator {
            get {
                return ResourceManager.GetString("TimeSpanExtensionsUnitSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} day.
        /// </summary>
        public static string TimeSpanToken1DayFormatString {
            get {
                return ResourceManager.GetString("TimeSpanToken1DayFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} hour.
        /// </summary>
        public static string TimeSpanToken1HourFormatString {
            get {
                return ResourceManager.GetString("TimeSpanToken1HourFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} minute.
        /// </summary>
        public static string TimeSpanToken1MinuteFormatString {
            get {
                return ResourceManager.GetString("TimeSpanToken1MinuteFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} month.
        /// </summary>
        public static string TimeSpanToken1MonthFormatString {
            get {
                return ResourceManager.GetString("TimeSpanToken1MonthFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} second.
        /// </summary>
        public static string TimeSpanToken1SecondFormatString {
            get {
                return ResourceManager.GetString("TimeSpanToken1SecondFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} week.
        /// </summary>
        public static string TimeSpanToken1WeekFormatString {
            get {
                return ResourceManager.GetString("TimeSpanToken1WeekFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} year.
        /// </summary>
        public static string TimeSpanToken1YearFormatString {
            get {
                return ResourceManager.GetString("TimeSpanToken1YearFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^
        ///(
        ///    \s*
        ///    (
        ///        (
        ///            (?&lt;years&gt;\d+|\d*[.,/]\d+)
        ///            \s*
        ///            (y|yrs?|years?)
        ///            (
        ///                \s*
        ///                (?&lt;months&gt;\d+|\d*[.,/]\d+)
        ///                (\s+|$)
        ///            )?
        ///        )
        ///        |
        ///        (
        ///            (?&lt;months&gt;\d+|\d*[.,/]\d+)
        ///            \s*
        ///            (mo|mon?s?|months?)
        ///            (
        ///                \s*
        ///                (?&lt;days&gt;\d+|\d*[.,/]\d+)
        ///                (\s+|$)
        ///            )?
        ///        )
        ///        |
        ///        ( [rest of string was truncated]&quot;;.
        /// </summary>
        public static string TimeSpanTokenLongFormPattern {
            get {
                return ResourceManager.GetString("TimeSpanTokenLongFormPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^
        ///\s*
        ///(?&lt;minutes&gt;\d+)
        ///\s*
        ///$.
        /// </summary>
        public static string TimeSpanTokenMinutesOnlyPattern {
            get {
                return ResourceManager.GetString("TimeSpanTokenMinutesOnlyPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} days.
        /// </summary>
        public static string TimeSpanTokenNDaysFormatString {
            get {
                return ResourceManager.GetString("TimeSpanTokenNDaysFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} hours.
        /// </summary>
        public static string TimeSpanTokenNHoursFormatString {
            get {
                return ResourceManager.GetString("TimeSpanTokenNHoursFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} minutes.
        /// </summary>
        public static string TimeSpanTokenNMinutesFormatString {
            get {
                return ResourceManager.GetString("TimeSpanTokenNMinutesFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} months.
        /// </summary>
        public static string TimeSpanTokenNMonthsFormatString {
            get {
                return ResourceManager.GetString("TimeSpanTokenNMonthsFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} seconds.
        /// </summary>
        public static string TimeSpanTokenNSecondsFormatString {
            get {
                return ResourceManager.GetString("TimeSpanTokenNSecondsFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} weeks.
        /// </summary>
        public static string TimeSpanTokenNWeeksFormatString {
            get {
                return ResourceManager.GetString("TimeSpanTokenNWeeksFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} years.
        /// </summary>
        public static string TimeSpanTokenNYearsFormatString {
            get {
                return ResourceManager.GetString("TimeSpanTokenNYearsFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^
        ///\s*
        ///(
        ///    (
        ///        (
        ///            (
        ///                (?&lt;years&gt;\d+)
        ///                \s*[.,:\s]\s*
        ///            )?
        ///            (?&lt;months&gt;\d+)
        ///            \s*[.,:\s]\s*
        ///        )?
        ///        (?&lt;days&gt;\d+)
        ///        \s*[.,:\s]\s*
        ///    )?
        ///    (?&lt;hours&gt;\d+)
        ///    \s*[.,:\s]\s*
        ///)?
        ///(?&lt;minutes&gt;\d+)
        ///\s*[.,:\s]\s*
        ///(?&lt;seconds&gt;\d+)
        ///\s*
        ///$.
        /// </summary>
        public static string TimeSpanTokenShortFormPattern {
            get {
                return ResourceManager.GetString("TimeSpanTokenShortFormPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  .
        /// </summary>
        public static string TimeSpanTokenUnitSeparator {
            get {
                return ResourceManager.GetString("TimeSpanTokenUnitSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon TrayIcon {
            get {
                object obj = ResourceManager.GetObject("TrayIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage: {0} [OPTIONS] [&lt;input&gt;]
        ///A simple countdown timer for Windows.
        ///
        ///  &lt;input&gt;
        ///        The input used to start the timer.
        ///
        ///        For example:
        ///        &quot;5&quot;                     count down for 5 minutes
        ///        &quot;5:30&quot;                  count down for 5 minutes 30 seconds
        ///        &quot;7:30:00&quot;               count down for 7 hours 30 minutes
        ///        &quot;5 minutes&quot;             count down for 5 minutes
        ///        &quot;5 minutes 30 seconds&quot;  count down for 5 minutes 30 seconds
        ///        &quot;7 hours 30 minutes&quot;    count d [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Usage {
            get {
                return ResourceManager.GetString("Usage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Hourglass.
        /// </summary>
        public static string UsageDialogAboutHourglassHyperlinkText {
            get {
                return ResourceManager.GetString("UsageDialogAboutHourglassHyperlinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Close.
        /// </summary>
        public static string UsageDialogCloseButtonContent {
            get {
                return ResourceManager.GetString("UsageDialogCloseButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command-line usage.
        /// </summary>
        public static string UsageDialogDefaultMessageText {
            get {
                return ResourceManager.GetString("UsageDialogDefaultMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hourglass.
        /// </summary>
        public static string UsageDialogTitle {
            get {
                return ResourceManager.GetString("UsageDialogTitle", resourceCulture);
            }
        }
    }
}
