//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hourglass.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Hourglass.Serialization.TimerInfoList Timers {
            get {
                return ((global::Hourglass.Serialization.TimerInfoList)(this["Timers"]));
            }
            set {
                this["Timers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Hourglass.Serialization.TimerInputInfoList Inputs {
            get {
                return ((global::Hourglass.Serialization.TimerInputInfoList)(this["Inputs"]));
            }
            set {
                this["Inputs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Hourglass.Serialization.TimerOptionsInfo MostRecentOptions {
            get {
                return ((global::Hourglass.Serialization.TimerOptionsInfo)(this["MostRecentOptions"]));
            }
            set {
                this["MostRecentOptions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowInNotificationArea {
            get {
                return ((bool)(this["ShowInNotificationArea"]));
            }
            set {
                this["ShowInNotificationArea"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Hourglass.Serialization.WindowSizeInfo WindowSize {
            get {
                return ((global::Hourglass.Serialization.WindowSizeInfo)(this["WindowSize"]));
            }
            set {
                this["WindowSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Hourglass.Serialization.TimerColorInfoList Colors {
            get {
                return ((global::Hourglass.Serialization.TimerColorInfoList)(this["Colors"]));
            }
            set {
                this["Colors"] = value;
            }
        }
    }
}
